apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-website
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-website
  template:
    metadata:
      labels:
        app: test-website
    spec:
      containers:
        - name: test-website
          image: jana301/test-website:latest
          ports:
            - containerPort: 80
